### ISSUE TITLE
Substitute PID with IRI for attributes

### ISSUE THREAD

**Issue by rabuono** [ELIXIR-Belgium/ISA-merger#42]
We are now following nomenclature from SEEK
So in
```json
"pid": null,
"name": "Input",
"description": "Existing Samples in DataHub that represent input for this protocol.",
"dataType": "Registered Sample (multiple)",
"required": true,
"isaTag": null
``` 

`pid` must become `iri`

**Comment by floradanna** [comment]
please, check and align with https://github.com/seek4science/seek/issues/1010

**Comment by stuzart** [comment]
if you're talking about sample attribute fields, then don't change the pid attribute to iri, it would be incorrect. It would be like change a 'title' attribute to just 'string'. pid is it's purpose, iri is just the syntax
