### ISSUE TITLE
Metadata for each Template

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/ISA-merger#5]
It could be useful to describe each TEMPLATE that we create in the backend of SEEK (RS) with the following metadata:
- Name: √
- ID: RS √
- Date of creation: missing
- Version number (next to title): missing
- Repository of destination: missing
- ID and version of repository scheme
- ID and version of ISA configuration
- ISA Measurement type
- ISA Technology type
- ISA Protocol name
- Ontologies version
- Organism

This should make easy to search, sort and keep track of changes in our sample_types.

**Comment by vdkkia** [comment]
Using the custom metadata at the sample type level is a good solution.

**Comment by floradanna** [comment]
But custom metadata are visible to the end-user of the platform. These metadata don't have to be shown to the end-users.

**Comment by vdkkia** [comment]
Check availability to use the repositories standard to keep this information, or to create a brand new table for the templates.
