### ISSUE TITLE
Adapt ENA plant checklist to ISA

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/ISA-merger#9]
ENA plant checklist, that is now used as "source characteristics" template, needs to be adapt to the ISA Model.
Some attributes of this checklist have to be placed in different templates:
- source name[characteristics]
- sample collection protocol[parameter value]
- sample name[characteristics]
- nucleic acid extraction protocol[parameter value]
- ...to be checked

**Comment by rabuono** [comment]
This was on hold, along other changes, until we can make sure that we can remap it to the sample file for ENA.
